"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-17 01:27:58.290767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('template_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=False),
    sa.Column('age_max', sa.Integer(), nullable=False),
    sa.Column('income_segment', sa.String(), nullable=False),
    sa.Column('lifestyle', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('behavior_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('SEEDED', 'DYNAMIC', name='persona_source'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_key')
    )
    op.create_table('users',
    sa.Column('org_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('products',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('branding_details', sa.Text(), nullable=True),
    sa.Column('original_image_path', sa.String(), nullable=False),
    sa.Column('preprocessed_image_path', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_user_id'), 'products', ['user_id'], unique=False)
    op.create_table('simulations',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pricing_strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_demographic', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('promotional_messaging', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'SIMULATING', 'EVALUATING', 'OPTIMIZING', 'COMPLETED', 'FAILED', name='simulation_status'), nullable=False),
    sa.Column('iteration_count', sa.Integer(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_product_id'), 'simulations', ['product_id'], unique=False)
    op.create_index(op.f('ix_simulations_user_id'), 'simulations', ['user_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('simulation_id', sa.Uuid(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_method', sa.String(), nullable=False),
    sa.Column('fid_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_simulation_id'), 'product_variants', ['simulation_id'], unique=False)
    op.create_table('simulation_personas',
    sa.Column('simulation_id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('simulation_id', 'persona_id')
    )
    op.create_table('feedback',
    sa.Column('simulation_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('qualitative_text', sa.Text(), nullable=False),
    sa.Column('purchase_likelihood', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentiment_label'), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consistency_variance', sa.Float(), nullable=True),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_persona_id'), 'feedback', ['persona_id'], unique=False)
    op.create_index(op.f('ix_feedback_simulation_id'), 'feedback', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_feedback_variant_id'), 'feedback', ['variant_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('simulation_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_variant_id', sa.Uuid(), nullable=False),
    sa.Column('pmf_score', sa.Float(), nullable=False),
    sa.Column('ranking', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommended_variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_feedback_variant_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_simulation_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_persona_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_table('simulation_personas')
    op.drop_index(op.f('ix_product_variants_simulation_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_simulations_user_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_product_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_products_user_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('personas')
    # ### end Alembic commands ###

    # Autogenerate does not emit DROP TYPE for Postgres native enums (it only
    # manages tables/columns) -- without this, a downgrade-then-upgrade cycle
    # fails with "type already exists" on the next CREATE TYPE.
    sa.Enum(name='sentiment_label').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='simulation_status').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='persona_source').drop(op.get_bind(), checkfirst=False)
