"""reference tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-17 01:31:18.946800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_images',
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('original_image_url', sa.String(), nullable=False),
    sa.Column('image_type', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.Float(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('image_format', sa.String(), nullable=True),
    sa.Column('download_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_ref_images_product_id'), 'ref_images', ['product_id'], unique=False)
    op.create_table('ref_market',
    sa.Column('market_record_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.Column('price_type', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('availability', sa.String(), nullable=False),
    sa.Column('stock_status', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('market_record_id')
    )
    op.create_index(op.f('ix_ref_market_product_id'), 'ref_market', ['product_id'], unique=False)
    op.create_table('ref_product_intelligence',
    sa.Column('intelligence_record_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('brand_description', sa.Text(), nullable=True),
    sa.Column('brand_mission', sa.Text(), nullable=True),
    sa.Column('brand_values', sa.Text(), nullable=True),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('campaign_description', sa.Text(), nullable=True),
    sa.Column('campaign_theme', sa.String(), nullable=True),
    sa.Column('marketing_strategy', sa.Text(), nullable=True),
    sa.Column('target_age_min', sa.Integer(), nullable=True),
    sa.Column('target_age_max', sa.Integer(), nullable=True),
    sa.Column('target_gender', sa.String(), nullable=True),
    sa.Column('target_income_segment', sa.String(), nullable=True),
    sa.Column('target_region', sa.String(), nullable=True),
    sa.Column('target_lifestyle', sa.String(), nullable=True),
    sa.Column('brand_positioning', sa.Text(), nullable=True),
    sa.Column('brand_ambassador', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('product_family', sa.String(), nullable=True),
    sa.Column('parent_company', sa.String(), nullable=True),
    sa.Column('country_of_origin', sa.String(), nullable=True),
    sa.Column('launch_region', sa.String(), nullable=True),
    sa.Column('distribution_channels', sa.String(), nullable=True),
    sa.Column('sustainability_notes', sa.Text(), nullable=True),
    sa.Column('competitor_products', sa.Text(), nullable=True),
    sa.Column('competitor_brands', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('intelligence_record_id')
    )
    op.create_index(op.f('ix_ref_product_intelligence_product_id'), 'ref_product_intelligence', ['product_id'], unique=False)
    op.create_table('ref_products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('retail_price', sa.Float(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('image_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_record_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('product_intelligence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relationship_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('ref_reviews',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_review_id', sa.String(), nullable=True),
    sa.Column('review_title', sa.String(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('reviewer_name', sa.String(), nullable=True),
    sa.Column('verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('helpful_votes', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_ref_reviews_product_id'), 'ref_reviews', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ref_reviews_product_id'), table_name='ref_reviews')
    op.drop_table('ref_reviews')
    op.drop_table('ref_products')
    op.drop_index(op.f('ix_ref_product_intelligence_product_id'), table_name='ref_product_intelligence')
    op.drop_table('ref_product_intelligence')
    op.drop_index(op.f('ix_ref_market_product_id'), table_name='ref_market')
    op.drop_table('ref_market')
    op.drop_index(op.f('ix_ref_images_product_id'), table_name='ref_images')
    op.drop_table('ref_images')
    # ### end Alembic commands ###
